import MysUser from './MysUser.js';
export default class MysInfo {
    static tips: string;
    uid: any;
    e: any;
    userId: any;
    ckInfo: any;
    auth: any;
    gtest: any;
    mysButton: any;
    ckUser: any;
    constructor(e: any);
    static init(e: any, api: any): Promise<false | MysInfo>;
    static getUid(e: any, matchMsgUid?: boolean): Promise<any>;
    static getSelfUid(e: any): Promise<any>;
    static get(e: any, api: any, data?: {}, option?: {}): Promise<any>;
    static initPubCk(): Promise<void>;
    static initUserCk(): Promise<void>;
    static initing: any;
    static initCache(force?: boolean, clearData?: boolean): Promise<boolean>;
    static getBingCkUid(): Promise<{}>;
    static checkUidBing(uid: any, game?: string): Promise<false | MysUser>;
    static delDisable(): Promise<number>;
    checkAuth(api: any): boolean;
    checkReply(): Promise<void>;
    getCookie(game?: string, onlySelfCk?: boolean): any;
    checkCode(res: any, type: any, mysApi?: {}, data?: {}, isTask?: boolean): Promise<any>;
    delCk(): Promise<boolean>;
    disableToday(game?: string): Promise<void>;
}
