import BaseModel from './BaseModel.js';
export default class NoteUser extends BaseModel {
    db: any;
    qq: any;
    mysUsers: any;
    _map: any;
    constructor(qq: any);
    get uid(): any;
    get ckUids(): any[];
    get cks(): {};
    get hasCk(): boolean;
    static create(qq: any, db?: boolean): any;
    static forEach(fn: any): Promise<void>;
    initDB(db?: boolean): Promise<void>;
    initMysUser(): Promise<void>;
    save(): Promise<void>;
    getUidMapList(game?: string, type?: string): any;
    getUidData(uid?: string, game?: string): any;
    hasUid(uid?: string, game?: string): boolean;
    getCkUid(game?: string): any;
    getCkUidList(game?: string): any;
    getUid(game?: string): any;
    getUidList(game?: string): any;
    getMysUser(game?: string): any;
    addRegUid(uid: any, game?: string, save?: boolean): void;
    delRegUid(uid: any, game?: string): void;
    _games: {};
    getGameDs(game?: string): any;
    autoRegUid(uid?: string, game?: string): string;
    setMainUid(uid?: string, game?: string, save?: boolean): boolean;
    addMysUser(mysUser: any): Promise<void>;
    delCk(ltuid?: string): Promise<void>;
    delMysUser(mysUser?: any): Promise<void>;
    eachMysUser(fn: any): Promise<void>;
    eachAllMysUser(fn: any): Promise<void>;
    checkCk(): Promise<any[]>;
}
